# Generated by Django 3.0.7 on 2020-09-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_penerimaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50, verbose_name='Judul')),
                ('isi', models.TextField(verbose_name='isi')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='nisn',
            field=models.CharField(max_length=50, unique=True, verbose_name='NISN'),
        ),
    ]
