# Generated by Django 3.0.7 on 2020-09-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_penerimaan', '0002_auto_20200922_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelName',
            new_name='Pengumuman',
        ),
    ]
