# Generated by Django 3.0.7 on 2020-09-24 02:26

import django.core.validators
from django.db import migrations, models
import web_penerimaan.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_penerimaan', '0003_auto_20200922_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='isi',
            field=models.TextField(verbose_name='Isi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=web_penerimaan.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg']), web_penerimaan.models.file_size]),
        ),
    ]
