# Generated by Django 3.1.3 on 2020-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_penerimaan', '0005_auto_20201125_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nilai_skhu',
            field=models.FloatField(default=0.0),
        ),
    ]
