# Generated by Django 3.1.3 on 2020-11-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_penerimaan', '0006_student_nilai_skhu'),
    ]

    operations = [
        migrations.CreateModel(
            name='tombol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tombol', models.BooleanField(default=False)),
            ],
        ),
    ]
