# Generated by Django 3.1.4 on 2021-01-16 00:18

import django.core.validators
from django.db import migrations, models
import web_penerimaan.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_penerimaan', '0007_tombol'),
    ]

    operations = [
        migrations.CreateModel(
            name='alur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alur', models.FileField(null=True, upload_to=web_penerimaan.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg']), web_penerimaan.models.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='gambar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.FileField(null=True, upload_to=web_penerimaan.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg']), web_penerimaan.models.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='visimisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=50, null=True)),
                ('visimisi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(1, 'Siswa'), (2, 'Panitia'), (3, 'admin')], default=1),
        ),
    ]
